export enum ROLES {
    ADMIN = "ADMIN",
    INSTITUTE_ADMIN = "INSTITUTE_ADMIN",
    USER = "USER"
}


export enum ID_TYPE {
    ADMIN = ROLES.ADMIN,
    INSTITUTE = ROLES.INSTITUTE_ADMIN,
    USER = ROLES.USER
}